language: minimal

install:
- |
  wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
  bash ~/miniconda.sh -b -p $HOME/miniconda
  source "$HOME/miniconda/etc/profile.d/conda.sh"
  conda config --set always_yes yes
  conda update -q conda
  conda install python=3.7 bioconda::nextflow=19.07.0 conda-forge::pytest=5.1.2

script:
- |
  conda activate base
  nextflow run ctdna-snv-caller-comparison.nf -profile test

- |
  conda activate base
  mkdir unit_tests
  pytest --verbose --junitxml=unit_tests/junit.xml
