# git repo is cloned automatically
# base image is a minimal linux environment
language: minimal


install:
  # install miniconda and install packages into base environment
  - |
    cd ~
    wget https://github.com/sylabs/singularity/releases/download/v3.3.0/singularity-3.3.0.tar.gz
    tar -xzf singularity-3.3.0.tar.gz
    cd singularity
    ./mconfig
    make -C builddir
    sudo make -C builddir install
  - |
    wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O ~/miniconda.sh
    bash ~/miniconda.sh -b -p $HOME/miniconda
    source "$HOME/miniconda/etc/profile.d/conda.sh"
    conda config --set always_yes yes
    conda update -q conda
    conda install python=3.7 bioconda::nextflow=19.07.0 conda-forge::pytest=5.1.2


before_script:
  # activate the conda environment  before each script
  - conda activate base && cd /home/travis/build/erikwaskiewicz/ctdna-project


script:
  # pull the Sigularity images
  - |
    singularity pull --name ctdna-base-latest.simg docker://erikwaskiewicz/ctdna-base:latest
    singularity pull --name ctdna-sinvict-latest.simg docker://erikwaskiewicz/ctdna-sinvict:latest
    singularity pull --name ctdna-varscan-latest.simg docker://erikwaskiewicz/ctdna-varscan:latest
    
  # run the nextflow pipeline with the test data
  - nextflow run ctdna-snv-caller-comparison.nf \
      -profile test,singularity_conf \
      --singularity_cache="/home/travis/build/erikwaskiewicz/ctdna-project"

  # run the pytest unit tests on the pipeline output
  - pytest --verbose
